// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x4VgG6kzZCVuaqknYN7tgc
// Component: Dz8LagQJGg4_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectcss
import sty from "./PlasmicThemeSwitcher.module.css"; // plasmic-import: Dz8LagQJGg4_/css

createPlasmicElementProxy;

export type PlasmicThemeSwitcher__VariantMembers = {};
export type PlasmicThemeSwitcher__VariantsArgs = {};
type VariantPropType = keyof PlasmicThemeSwitcher__VariantsArgs;
export const PlasmicThemeSwitcher__VariantProps = new Array<VariantPropType>();

export type PlasmicThemeSwitcher__ArgsType = {};
type ArgPropType = keyof PlasmicThemeSwitcher__ArgsType;
export const PlasmicThemeSwitcher__ArgProps = new Array<ArgPropType>();

export type PlasmicThemeSwitcher__OverridesType = {
  root?: Flex__<"div">;
  dropdown?: Flex__<typeof AntdDropdown>;
  button?: Flex__<typeof AntdButton>;
};

export interface DefaultThemeSwitcherProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicThemeSwitcher__RenderFunc(props: {
  variants: PlasmicThemeSwitcher__VariantsArgs;
  args: PlasmicThemeSwitcher__ArgsType;
  overrides: PlasmicThemeSwitcher__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <AntdDropdown
        data-plasmic-name={"dropdown"}
        data-plasmic-override={overrides.dropdown}
        className={classNames("__wab_instance", sty.dropdown)}
        dropdownMenuScopeClassName={sty["dropdown__dropdownMenu"]}
        menuItems={() => (
          <React.Fragment>
            <AntdMenuItem
              className={classNames("__wab_instance", sty.menuItem__k7Oje)}
              key={"menu-item-1"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aqEdt
                )}
              >
                {"Menu item"}
              </div>
            </AntdMenuItem>
            <AntdMenuItem
              className={classNames("__wab_instance", sty.menuItem__ypOze)}
              key={"menu-item-2"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__e0Qhb
                )}
              >
                {"Menu item"}
              </div>
            </AntdMenuItem>
          </React.Fragment>
        )}
        menuItemsJson={(() => {
          const __composite = [
            { type: "item", value: "action1", label: null },
            { type: "item", value: "action2", label: null }
          ];
          __composite["0"]["label"] = "Pastel";
          __composite["1"]["label"] = "95";
          return __composite;
        })()}
      >
        <AntdButton
          data-plasmic-name={"button"}
          data-plasmic-override={overrides.button}
          className={classNames("__wab_instance", sty.button)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ce8Jt
            )}
          >
            {"Theme"}
          </div>
        </AntdButton>
      </AntdDropdown>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dropdown", "button"],
  dropdown: ["dropdown", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dropdown: typeof AntdDropdown;
  button: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicThemeSwitcher__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicThemeSwitcher__VariantsArgs;
    args?: PlasmicThemeSwitcher__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicThemeSwitcher__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicThemeSwitcher__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicThemeSwitcher__ArgProps,
          internalVariantPropNames: PlasmicThemeSwitcher__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicThemeSwitcher__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicThemeSwitcher";
  } else {
    func.displayName = `PlasmicThemeSwitcher.${nodeName}`;
  }
  return func;
}

export const PlasmicThemeSwitcher = Object.assign(
  // Top-level PlasmicThemeSwitcher renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dropdown: makeNodeComponent("dropdown"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicThemeSwitcher
    internalVariantProps: PlasmicThemeSwitcher__VariantProps,
    internalArgProps: PlasmicThemeSwitcher__ArgProps
  }
);

export default PlasmicThemeSwitcher;
/* prettier-ignore-end */
