// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x4VgG6kzZCVuaqknYN7tgc
// Component: on3V-1opBN4k

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Navbar from "../../Navbar"; // plasmic-import: 5THU1wffFibB/component
import Window from "../../Window"; // plasmic-import: BWjgdOwFY_OO/component
import YouTube from "@plasmicpkgs/react-youtube";
import WindowButton from "../../WindowButton"; // plasmic-import: KZYdo-R8GYAn/component

import { useScreenVariants as useScreenVariantsdmuurUfQuA6N } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: DmuurUFQuA6N/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectcss
import sty from "./PlasmicDisukoTv.module.css"; // plasmic-import: on3V-1opBN4k/css

createPlasmicElementProxy;

export type PlasmicDisukoTv__VariantMembers = {};
export type PlasmicDisukoTv__VariantsArgs = {};
type VariantPropType = keyof PlasmicDisukoTv__VariantsArgs;
export const PlasmicDisukoTv__VariantProps = new Array<VariantPropType>();

export type PlasmicDisukoTv__ArgsType = {};
type ArgPropType = keyof PlasmicDisukoTv__ArgsType;
export const PlasmicDisukoTv__ArgProps = new Array<ArgPropType>();

export type PlasmicDisukoTv__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  window?: Flex__<typeof Window>;
  windowButton?: Flex__<typeof WindowButton>;
};

export interface DefaultDisukoTvProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDisukoTv__RenderFunc(props: {
  variants: PlasmicDisukoTv__VariantsArgs;
  args: PlasmicDisukoTv__ArgsType;
  overrides: PlasmicDisukoTv__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsdmuurUfQuA6N()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />

        <link rel="canonical" href={PlasmicDisukoTv.pageMetadata.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <Window
            data-plasmic-name={"window"}
            data-plasmic-override={overrides.window}
            className={classNames("__wab_instance", sty.window)}
            windowText={"Film and YouTube Page Under Construction!"}
            windowTitle={"Notice:"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__soVfK
            )}
          >
            {"Latest Video:"}
          </div>
          <YouTube
            className={classNames("__wab_instance", sty.youTube__pbOqu)}
            videoId={"IbgGUF6DuZw"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cQvt2
            )}
          >
            {"Featured Videos:"}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__pOeY)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bG8Vr
              )}
            >
              {"Film + Video Production"}
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___15XOr)}
            >
              <YouTube
                className={classNames("__wab_instance", sty.youTube__jxMd2)}
                videoId={"5lbSvQbllUs"}
              />

              <YouTube
                className={classNames("__wab_instance", sty.youTube__bt9Jc)}
                videoId={"XI30lZMrOoA"}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___2Jv9Y)}
            >
              <YouTube
                className={classNames("__wab_instance", sty.youTube__sLc1T)}
                videoId={"c9gd_szKhcg"}
              />

              <YouTube
                className={classNames("__wab_instance", sty.youTube__iWfLn)}
                videoId={"yHNOJKyBp_4"}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__h9FKw)}
            >
              <YouTube
                className={classNames("__wab_instance", sty.youTube___37Wk0)}
                videoId={"XkEfUyL0aA0"}
              />

              <YouTube
                className={classNames("__wab_instance", sty.youTube__ppHEr)}
                videoId={"IbgGUF6DuZw"}
              />
            </Stack__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rwLhz
              )}
            >
              {"Visual Effects / Animation"}
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___8HnN1)}
            >
              <YouTube
                className={classNames("__wab_instance", sty.youTube__xp5LW)}
                videoId={"DLiNRjd395w"}
              />

              <YouTube
                className={classNames("__wab_instance", sty.youTube__lzTyL)}
                videoId={"UROiJOriRqE"}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__p3RQf)}
            >
              <YouTube
                className={classNames("__wab_instance", sty.youTube___5SiJ8)}
                videoId={"LPWDiN1b5vE"}
              />

              <YouTube
                className={classNames("__wab_instance", sty.youTube__uiKjy)}
                videoId={"pegx7KEoYoA"}
              />
            </Stack__>
          </div>
          <WindowButton
            data-plasmic-name={"windowButton"}
            data-plasmic-override={overrides.windowButton}
            className={classNames("__wab_instance", sty.windowButton)}
            link={`/portfolio`}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nylMx
              )}
            >
              {"<- Back To Portfolio"}
            </div>
          </WindowButton>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navbar", "window", "windowButton"],
  navbar: ["navbar"],
  window: ["window"],
  windowButton: ["windowButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  window: typeof Window;
  windowButton: typeof WindowButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDisukoTv__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDisukoTv__VariantsArgs;
    args?: PlasmicDisukoTv__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDisukoTv__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDisukoTv__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDisukoTv__ArgProps,
          internalVariantPropNames: PlasmicDisukoTv__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDisukoTv__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDisukoTv";
  } else {
    func.displayName = `PlasmicDisukoTv.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "x4VgG6kzZCVuaqknYN7tgc"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicDisukoTv = Object.assign(
  // Top-level PlasmicDisukoTv renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    window: makeNodeComponent("window"),
    windowButton: makeNodeComponent("windowButton"),

    // Metadata about props expected for PlasmicDisukoTv
    internalVariantProps: PlasmicDisukoTv__VariantProps,
    internalArgProps: PlasmicDisukoTv__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: "https://disuko.gay/disuko-tv"
    }
  }
);

export default PlasmicDisukoTv;
/* prettier-ignore-end */
