// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x4VgG6kzZCVuaqknYN7tgc
// Component: 3GOrKOgLh0ga

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Navbar from "../../Navbar"; // plasmic-import: 5THU1wffFibB/component
import WindowButton from "../../WindowButton"; // plasmic-import: KZYdo-R8GYAn/component
import Window from "../../Window"; // plasmic-import: BWjgdOwFY_OO/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: 3K9IqsAFaaID/globalVariant
import { useScreenVariants as useScreenVariantsdmuurUfQuA6N } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: DmuurUFQuA6N/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectcss
import sty from "./PlasmicPortfolio3DDesign.module.css"; // plasmic-import: 3GOrKOgLh0ga/css

createPlasmicElementProxy;

export type PlasmicPortfolio3DDesign__VariantMembers = {};
export type PlasmicPortfolio3DDesign__VariantsArgs = {};
type VariantPropType = keyof PlasmicPortfolio3DDesign__VariantsArgs;
export const PlasmicPortfolio3DDesign__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPortfolio3DDesign__ArgsType = {};
type ArgPropType = keyof PlasmicPortfolio3DDesign__ArgsType;
export const PlasmicPortfolio3DDesign__ArgProps = new Array<ArgPropType>();

export type PlasmicPortfolio3DDesign__OverridesType = {
  _3DDesign?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  windowButton?: Flex__<typeof WindowButton>;
  imageWindow4?: Flex__<"div">;
  imageWindow5?: Flex__<"div">;
  imageWindow10?: Flex__<"div">;
  imageWindow6?: Flex__<"div">;
  imageWindow7?: Flex__<"div">;
  imageWindow11?: Flex__<"div">;
  imageWindow8?: Flex__<"div">;
  imageWindow9?: Flex__<"div">;
  imageWindow12?: Flex__<"div">;
  imageWindow13?: Flex__<"div">;
  imageWindow14?: Flex__<"div">;
  imageWindow15?: Flex__<"div">;
  imageWindow?: Flex__<"div">;
  imageWindow2?: Flex__<"div">;
  imageWindow3?: Flex__<"div">;
  cad2?: Flex__<typeof SliderWrapper>;
  cad?: Flex__<typeof SliderWrapper>;
};

export interface DefaultPortfolio3DDesignProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPortfolio3DDesign__RenderFunc(props: {
  variants: PlasmicPortfolio3DDesign__VariantsArgs;
  args: PlasmicPortfolio3DDesign__ArgsType;
  overrides: PlasmicPortfolio3DDesign__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "cad.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "cad",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      },
      {
        path: "cad2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "cad2",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    theme: useTheme(),
    screen: useScreenVariantsdmuurUfQuA6N()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicPortfolio3DDesign.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPortfolio3DDesign.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPortfolio3DDesign.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"_3DDesign"}
        data-plasmic-override={overrides._3DDesign}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty._3DDesign,
          {
            [projectcss.global_theme_classic]: hasVariant(
              globalVariants,
              "theme",
              "classic"
            ),
            [sty._3DDesignglobal_theme_classic]: hasVariant(
              globalVariants,
              "theme",
              "classic"
            )
          }
        )}
      >
        <Navbar
          data-plasmic-name={"navbar"}
          data-plasmic-override={overrides.navbar}
          className={classNames("__wab_instance", sty.navbar)}
        />

        <WindowButton
          data-plasmic-name={"windowButton"}
          data-plasmic-override={overrides.windowButton}
          className={classNames("__wab_instance", sty.windowButton)}
          link={`/portfolio`}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__eAa7U
            )}
          >
            {"<- Back To Portfolio"}
          </div>
        </WindowButton>
        <div className={classNames(projectcss.all, sty.freeBox__rhhmw)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___2UtR)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "100%"
                : "155px"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/disuko_website_retro_version/images/_3DdesignPng.png",
              fullWidth: 1467,
              fullHeight: 566,
              aspectRatio: undefined
            }}
          />
        </div>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__t4YO)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__v6MMb,
              {
                [sty.textglobal_theme_classic__v6MMbeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {"Low Poly Game Characters"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___2Sk7M,
              {
                [sty.textglobal_theme_classic___2Sk7MeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {'"Diko" - PANDAMONIUM: Diko Dating Sim (Red Panda Studios)'}
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__dav6A)}
          >
            <div
              data-plasmic-name={"imageWindow4"}
              data-plasmic-override={overrides.imageWindow4}
              className={classNames(projectcss.all, sty.imageWindow4, {
                [sty.imageWindow4global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__hdYm, {
                  [sty.imgglobal_theme_classic__hdYMeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image79.png",
                  fullWidth: 512,
                  fullHeight: 512,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow5"}
              data-plasmic-override={overrides.imageWindow5}
              className={classNames(projectcss.all, sty.imageWindow5, {
                [sty.imageWindow5global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__mgQa, {
                  [sty.imgglobal_theme_classic__mgQaENktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image84.png",
                  fullWidth: 553,
                  fullHeight: 550,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow10"}
              data-plasmic-override={overrides.imageWindow10}
              className={classNames(projectcss.all, sty.imageWindow10, {
                [sty.imageWindow10global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__zm2Bx, {
                  [sty.imgglobal_theme_classic__zm2BXeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image87.png",
                  fullWidth: 1919,
                  fullHeight: 1044,
                  aspectRatio: undefined
                }}
              />
            </div>
          </Stack__>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__i4MX,
              {
                [sty.textglobal_theme_classic__i4MXeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {'"Shiku" - PANDAMONIUM: Diko Dating Sim (Red Panda Studios)'}
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___5DrSp)}
          >
            <div
              data-plasmic-name={"imageWindow6"}
              data-plasmic-override={overrides.imageWindow6}
              className={classNames(projectcss.all, sty.imageWindow6, {
                [sty.imageWindow6global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__gDmct, {
                  [sty.imgglobal_theme_classic__gDmcteNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image82.png",
                  fullWidth: 512,
                  fullHeight: 512,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow7"}
              data-plasmic-override={overrides.imageWindow7}
              className={classNames(projectcss.all, sty.imageWindow7, {
                [sty.imageWindow7global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__m7DyF, {
                  [sty.imgglobal_theme_classic__m7DyFeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image83.png",
                  fullWidth: 553,
                  fullHeight: 550,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow11"}
              data-plasmic-override={overrides.imageWindow11}
              className={classNames(projectcss.all, sty.imageWindow11, {
                [sty.imageWindow11global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___1Nn48, {
                  [sty.imgglobal_theme_classic___1Nn48ENktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image88.png",
                  fullWidth: 1919,
                  fullHeight: 1046,
                  aspectRatio: undefined
                }}
              />
            </div>
          </Stack__>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___9W6WW,
              {
                [sty.textglobal_theme_classic___9W6WWeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {
              '"Customizable Racoon Player" - PANDAMONIUM: Diko Dating Sim (Red Panda Studios)'
            }
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___7Tm1J)}
          >
            <div
              data-plasmic-name={"imageWindow8"}
              data-plasmic-override={overrides.imageWindow8}
              className={classNames(projectcss.all, sty.imageWindow8, {
                [sty.imageWindow8global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__tuJzi, {
                  [sty.imgglobal_theme_classic__tuJzieNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image85.png",
                  fullWidth: 512,
                  fullHeight: 512,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow9"}
              data-plasmic-override={overrides.imageWindow9}
              className={classNames(projectcss.all, sty.imageWindow9, {
                [sty.imageWindow9global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__exKe8, {
                  [sty.imgglobal_theme_classic__exKe8ENktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image89.png",
                  fullWidth: 512,
                  fullHeight: 512,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow12"}
              data-plasmic-override={overrides.imageWindow12}
              className={classNames(projectcss.all, sty.imageWindow12, {
                [sty.imageWindow12global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__t9VfW, {
                  [sty.imgglobal_theme_classic__t9VfWeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image90.png",
                  fullWidth: 512,
                  fullHeight: 512,
                  aspectRatio: undefined
                }}
              />
            </div>
          </Stack__>
        </Stack__>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__yjyJc)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cZqKj,
              {
                [sty.textglobal_theme_classic__cZqKJeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {"Low Poly Environments"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lBJn,
              {
                [sty.textglobal_theme_classic__lBJNeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {
              '"Le Chunk E Chonks Office" - PANDAMONIUM: Diko Dating Sim (Red Panda Studios)'
            }
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__bjVlK)}
          >
            <div
              data-plasmic-name={"imageWindow13"}
              data-plasmic-override={overrides.imageWindow13}
              className={classNames(projectcss.all, sty.imageWindow13, {
                [sty.imageWindow13global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ysJDv, {
                  [sty.imgglobal_theme_classic__ysJDveNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/ezgifComOptimizeGif.gif",
                  fullWidth: 1920,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
              />
            </div>
          </Stack__>
        </Stack__>
        <div className={classNames(projectcss.all, sty.freeBox__fSznd)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vt2Fw,
              {
                [sty.textglobal_theme_classic__vt2FweNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {
              '"Balisong Oil Designs" - Promotional Material for Carbon Honey and Canto Group Balisong Oil'
            }
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__wiO8G)}
          >
            <div
              data-plasmic-name={"imageWindow14"}
              data-plasmic-override={overrides.imageWindow14}
              className={classNames(projectcss.all, sty.imageWindow14, {
                [sty.imageWindow14global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__qKhOi, {
                  [sty.imgglobal_theme_classic__qKhOieNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"100%"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image91.png",
                  fullWidth: 512,
                  fullHeight: 512,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow15"}
              data-plasmic-override={overrides.imageWindow15}
              className={classNames(projectcss.all, sty.imageWindow15, {
                [sty.imageWindow15global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___3LgTd, {
                  [sty.imgglobal_theme_classic___3LgTdeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"100%"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image92.png",
                  fullWidth: 512,
                  fullHeight: 512,
                  aspectRatio: undefined
                }}
              />
            </div>
          </Stack__>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__l9NJu,
              {
                [sty.textglobal_theme_classic__l9NJueNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {"Easel Renders"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__bgqRg,
              {
                [sty.textglobal_theme_classic__bgqRGeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {
              "Created for a vertically mounted display installation in the Chatham University Library."
            }
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__lmIi2)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__eowsj)}
            >
              <Window
                className={classNames("__wab_instance", sty.window__qkSdZ)}
                windowImage={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__s3M27)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/disuko_website_retro_version/images/animestreetWebp.webp",
                      fullWidth: 800,
                      fullHeight: 1422,
                      aspectRatio: undefined
                    }}
                  />
                }
                windowText={"Pastel Street"}
                windowTitle={"Easel Render"}
              />

              <Window
                className={classNames("__wab_instance", sty.window__nbokm)}
                windowImage={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__axSxY)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/disuko_website_retro_version/images/smartiesWebp.webp",
                      fullWidth: 600,
                      fullHeight: 1067,
                      aspectRatio: undefined
                    }}
                  />
                }
                windowText={"Smarties"}
                windowTitle={"Easel Render"}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___1FTxE)}
            >
              <Window
                className={classNames("__wab_instance", sty.window__uPusq)}
                windowImage={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__eqQnm)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/disuko_website_retro_version/images/strawberrymilkWebp.webp",
                      fullWidth: 800,
                      fullHeight: 1422,
                      aspectRatio: undefined
                    }}
                  />
                }
                windowText={"Strawberry Milk"}
                windowTitle={"Easel Render"}
              />

              <Window
                className={classNames("__wab_instance", sty.window__zUeqR)}
                windowImage={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__bD97C)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/disuko_website_retro_version/images/ramuneWebp2.webp",
                      fullWidth: 600,
                      fullHeight: 1067,
                      aspectRatio: undefined
                    }}
                  />
                }
                windowText={"Blueberry Ramune"}
                windowTitle={"Easel Render"}
              />
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__vXtFs)}>
              <Window
                className={classNames("__wab_instance", sty.window__nwxc)}
                windowImage={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___7GXkJ)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/disuko_website_retro_version/images/cakePopWebp.webp",
                      fullWidth: 800,
                      fullHeight: 1422,
                      aspectRatio: undefined
                    }}
                  />
                }
                windowText={"Kawaii Cake Pop"}
                windowTitle={"Easel Render"}
              />
            </div>
          </div>
        </div>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__rL1)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__wzKkh,
              {
                [sty.textglobal_theme_classic__wzKkheNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {"Characters"}
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__isLqW)}
          >
            <div
              data-plasmic-name={"imageWindow"}
              data-plasmic-override={overrides.imageWindow}
              className={classNames(projectcss.all, sty.imageWindow, {
                [sty.imageWindowglobal_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___3OVyV, {
                  [sty.imgglobal_theme_classic___3OVyVeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image67.gif",
                  fullWidth: 600,
                  fullHeight: 338,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow2"}
              data-plasmic-override={overrides.imageWindow2}
              className={classNames(projectcss.all, sty.imageWindow2, {
                [sty.imageWindow2global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__uRg3H, {
                  [sty.imgglobal_theme_classic__uRg3HeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "auto"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/licavoliSherbPoseTransparentPng.png",
                  fullWidth: 426,
                  fullHeight: 621,
                  aspectRatio: undefined
                }}
              />
            </div>
            <div
              data-plasmic-name={"imageWindow3"}
              data-plasmic-override={overrides.imageWindow3}
              className={classNames(projectcss.all, sty.imageWindow3, {
                [sty.imageWindow3global_theme_classic]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__yFmFd, {
                  [sty.imgglobal_theme_classic__yFmFDeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
                displayHeight={"338px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/image68.gif",
                  fullWidth: 256,
                  fullHeight: 256,
                  aspectRatio: undefined
                }}
              />
            </div>
          </Stack__>
        </Stack__>
        <div className={classNames(projectcss.all, sty.freeBox__d2Fcp)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__zOvZc,
              {
                [sty.textglobal_theme_classic__zOvZCeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              }
            )}
          >
            {"CAD & 3D Printing"}
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__gR1Cg)}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__rFRe6, {
                [sty.freeBoxglobal_theme_classic__rFRe6ENktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hxj9E,
                  {
                    [sty.textglobal_theme_classic__hxj9EeNktM]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  }
                )}
              >
                {"The Boba-song Butterfly Knife Trainer"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___19TbC,
                  {
                    [sty.textglobal_theme_classic___19TbCeNktM]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  }
                )}
              >
                {'"Create With Nabalis" Contest Top 10 of 100 Submissions'}
              </div>
              {(() => {
                const child$Props = {
                  arrowColor: true ? "#AF3386" : undefined,
                  beforeChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "currentSlide",
                      ["cad2", "currentSlide"],
                      SliderWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  centerMode: true,
                  className: classNames("__wab_instance", sty.cad2),
                  initialSlide: generateStateValueProp($state, [
                    "cad2",
                    "currentSlide"
                  ]),
                  ref: ref => {
                    $refs["cad2"] = ref;
                  },
                  sliderScopeClassName: sty["cad2__slider"]
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "currentSlide",
                      plasmicStateName: "cad2.currentSlide"
                    }
                  ],
                  [],
                  SliderWrapper_Helpers ?? {},
                  child$Props
                );

                return (
                  <SliderWrapper
                    data-plasmic-name={"cad2"}
                    data-plasmic-override={overrides.cad2}
                    {...child$Props}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xQsMi)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__jsDkk)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/mainImage2Png.png",
                          fullWidth: 1080,
                          fullHeight: 1080,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nIyBf)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__yHQwz)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/notableFeaturesPng.png",
                          fullWidth: 1080,
                          fullHeight: 1080,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___6P13G
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___8YT3K)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/colorConceptsPng.png",
                          fullWidth: 1080,
                          fullHeight: 1080,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__w4N5A)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__gZao0)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/screenshot20240311163819Png.png",
                          fullWidth: 1522,
                          fullHeight: 895,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </SliderWrapper>
                );
              })()}
            </div>
            <div
              className={classNames(projectcss.all, sty.freeBox__lu5Mk, {
                [sty.freeBoxglobal_theme_classic__lu5MKeNktM]: hasVariant(
                  globalVariants,
                  "theme",
                  "classic"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lr6B8,
                  {
                    [sty.textglobal_theme_classic__lr6B8ENktM]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  }
                )}
              >
                {"Disuko Rhythm Game Console"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hoyqU,
                  {
                    [sty.textglobal_theme_classic__hoyqUeNktM]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  }
                )}
              >
                {
                  "Project for the Chatham University Immersive Media Studio Space"
                }
              </div>
              {(() => {
                const child$Props = {
                  arrowColor: true ? "#AF3386" : undefined,
                  beforeChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "currentSlide",
                      ["cad", "currentSlide"],
                      SliderWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  centerMode: true,
                  className: classNames("__wab_instance", sty.cad),
                  initialSlide: generateStateValueProp($state, [
                    "cad",
                    "currentSlide"
                  ]),
                  ref: ref => {
                    $refs["cad"] = ref;
                  },
                  sliderScopeClassName: sty["cad__slider"]
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "currentSlide",
                      plasmicStateName: "cad.currentSlide"
                    }
                  ],
                  [],
                  SliderWrapper_Helpers ?? {},
                  child$Props
                );

                return (
                  <SliderWrapper
                    data-plasmic-name={"cad"}
                    data-plasmic-override={overrides.cad}
                    {...child$Props}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hjAjT)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__pqmqf)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/consoleShellWipJpg.jpg",
                          fullWidth: 800,
                          fullHeight: 600,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wWj1O,
                          {
                            [sty.textglobal_theme_classic__wWj1OeNktM]:
                              hasVariant(globalVariants, "theme", "classic")
                          }
                        )}
                      >
                        {
                          "Designing a shell for a mini rhythm game console in fusion 360."
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cwDp4)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__y1Xfh)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/consoleShellPrintsJpg.jpg",
                          fullWidth: 800,
                          fullHeight: 600,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qNSh7,
                          {
                            [sty.textglobal_theme_classic__qNSh7ENktM]:
                              hasVariant(globalVariants, "theme", "classic")
                          }
                        )}
                      >
                        {
                          "Iterating with prototypes to fit electronic components."
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__idNuc)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__mZbTl)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/disukoRhythmGameSp24Jpg.jpg",
                          fullWidth: 1080,
                          fullHeight: 1080,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oP1K,
                          {
                            [sty.textglobal_theme_classic__oP1KENktM]:
                              hasVariant(globalVariants, "theme", "classic")
                          }
                        )}
                      >
                        {"The final console!"}
                      </div>
                    </div>
                  </SliderWrapper>
                );
              })()}
            </div>
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  _3DDesign: [
    "_3DDesign",
    "navbar",
    "windowButton",
    "imageWindow4",
    "imageWindow5",
    "imageWindow10",
    "imageWindow6",
    "imageWindow7",
    "imageWindow11",
    "imageWindow8",
    "imageWindow9",
    "imageWindow12",
    "imageWindow13",
    "imageWindow14",
    "imageWindow15",
    "imageWindow",
    "imageWindow2",
    "imageWindow3",
    "cad2",
    "cad"
  ],
  navbar: ["navbar"],
  windowButton: ["windowButton"],
  imageWindow4: ["imageWindow4"],
  imageWindow5: ["imageWindow5"],
  imageWindow10: ["imageWindow10"],
  imageWindow6: ["imageWindow6"],
  imageWindow7: ["imageWindow7"],
  imageWindow11: ["imageWindow11"],
  imageWindow8: ["imageWindow8"],
  imageWindow9: ["imageWindow9"],
  imageWindow12: ["imageWindow12"],
  imageWindow13: ["imageWindow13"],
  imageWindow14: ["imageWindow14"],
  imageWindow15: ["imageWindow15"],
  imageWindow: ["imageWindow"],
  imageWindow2: ["imageWindow2"],
  imageWindow3: ["imageWindow3"],
  cad2: ["cad2"],
  cad: ["cad"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  _3DDesign: "div";
  navbar: typeof Navbar;
  windowButton: typeof WindowButton;
  imageWindow4: "div";
  imageWindow5: "div";
  imageWindow10: "div";
  imageWindow6: "div";
  imageWindow7: "div";
  imageWindow11: "div";
  imageWindow8: "div";
  imageWindow9: "div";
  imageWindow12: "div";
  imageWindow13: "div";
  imageWindow14: "div";
  imageWindow15: "div";
  imageWindow: "div";
  imageWindow2: "div";
  imageWindow3: "div";
  cad2: typeof SliderWrapper;
  cad: typeof SliderWrapper;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPortfolio3DDesign__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPortfolio3DDesign__VariantsArgs;
    args?: PlasmicPortfolio3DDesign__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPortfolio3DDesign__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPortfolio3DDesign__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPortfolio3DDesign__ArgProps,
          internalVariantPropNames: PlasmicPortfolio3DDesign__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPortfolio3DDesign__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "_3DDesign") {
    func.displayName = "PlasmicPortfolio3DDesign";
  } else {
    func.displayName = `PlasmicPortfolio3DDesign.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "x4VgG6kzZCVuaqknYN7tgc"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicPortfolio3DDesign = Object.assign(
  // Top-level PlasmicPortfolio3DDesign renders the root element
  withUsePlasmicAuth(makeNodeComponent("_3DDesign")),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    windowButton: makeNodeComponent("windowButton"),
    imageWindow4: makeNodeComponent("imageWindow4"),
    imageWindow5: makeNodeComponent("imageWindow5"),
    imageWindow10: makeNodeComponent("imageWindow10"),
    imageWindow6: makeNodeComponent("imageWindow6"),
    imageWindow7: makeNodeComponent("imageWindow7"),
    imageWindow11: makeNodeComponent("imageWindow11"),
    imageWindow8: makeNodeComponent("imageWindow8"),
    imageWindow9: makeNodeComponent("imageWindow9"),
    imageWindow12: makeNodeComponent("imageWindow12"),
    imageWindow13: makeNodeComponent("imageWindow13"),
    imageWindow14: makeNodeComponent("imageWindow14"),
    imageWindow15: makeNodeComponent("imageWindow15"),
    imageWindow: makeNodeComponent("imageWindow"),
    imageWindow2: makeNodeComponent("imageWindow2"),
    imageWindow3: makeNodeComponent("imageWindow3"),
    cad2: makeNodeComponent("cad2"),
    cad: makeNodeComponent("cad"),

    // Metadata about props expected for PlasmicPortfolio3DDesign
    internalVariantProps: PlasmicPortfolio3DDesign__VariantProps,
    internalArgProps: PlasmicPortfolio3DDesign__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "3D Design",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPortfolio3DDesign;
/* prettier-ignore-end */
